name: Stop bots on Vultr VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute commands over SSH on Vultr VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_VM_HOST }}
          username: ${{ secrets.VULTR_VM_USERNAME }}
          key: ${{ secrets.VULTR_VM_SSH_KEY }}
          password: ${{ secrets.VULTR_VM_PASSWORD }}
          script: |
            export SERVICE_NAME=telegram2notion
            export REPO_DIR=/root/telegram2notion
            
            systemctl stop SERVICE_NAME || true
            rm -rf $REPO_DIR
